// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imnxftwmejdcfhanfusv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbnhmdHdtZWpkY2ZoYW5mdXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjQxNzgsImV4cCI6MjA3MDgwMDE3OH0.qS8dTY9WyiOjq9Bo7PfN-if6RHYVJ7AZq96zhLd2Xdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});